### ISSUE TITLE
Getting this error on windows

### ISSUE THREAD

**Issue by Ejasackey** [yeboah326/random-question-generator#5]
![image](https://user-images.githubusercontent.com/52535990/189460419-47f35a82-236e-45b8-a64f-04b56cfa70ff.png)
@rocksongabriel

**Comment by yeboah326** [comment]
Fixed with https://github.com/yeboah326/random-question-generator/commit/ffe1294ec2bb539d9ba4c3c4e31f693dc6f2704b
